In [12]:
import torch

In [ ]:
import pandas as pd
import os

file_path = r"c:\Users\saady\Documents\project_trading_ai\Ai_Trading\app\MLearning\MVP ML\data\data_final_with_vmd_features.parquet"

df = pd.read_parquet(file_path)
print(df.head())

In [14]:
df.columns

Index(['Open time', 'Open_diff', 'High_diff', 'Low_diff', 'Close_diff',
       'Volume', 'Close time', 'hour_sin', 'hour_cos', 'day_of_week_sin',
       'day_of_week_cos', 'month_sin', 'month_cos', 'Label_Q_Standard',
       'Label_Q_VWAP', 'Label_Q_Gap', 'VMD_Mode1', 'VMD_Mode2', 'VMD_Mode3'],
      dtype='object')

In [17]:
df.describe()

,Open time,Open_diff,High_diff,Low_diff,Close_diff,Volume,Close time,hour_sin,hour_cos,day_of_week_sin,day_of_week_cos,month_sin,month_cos,Label_Q_Standard,Label_Q_VWAP,Label_Q_Gap,VMD_Mode1,VMD_Mode2,VMD_Mode3
count,280031,280031.000000,2.800310e+05,2.800310e+05,280031.000000,280031.000000,280031,280031.000000,280031.000000,280031.000000,280031.000000,280031.000000,280031.000000,280031.000000,280031.000000,280031.000000,281031.000000,281031.000000,281031.000000
mean,2022-01-13 12:48:25.730079744,0.001537,2.961735e-02,-2.937541e-02,0.001383,0.060815,2022-01-13 13:03:25.711946752,-0.000703,-0.000119,-0.000841,0.146060,-0.002629,-0.003083,0.490467,0.541070,0.500764,0.000037,0.000211,-0.001918
min,2018-01-11 12:00:00,-1633.644380,-2.051661e+03,-1.930698e+03,-1632.300024,-4.500288,2018-01-11 12:14:59.999000,-0.707107,-0.707107,-0.623490,-0.445042,-0.732051,-0.732051,-3718.705716,-1710.513810,-2.309478,-402.045012,-390.056103,-326.267274
25%,2020-01-14 14:22:30,-0.491834,-5.112144e-01,-4.795967e-01,-0.492403,-0.464388,2020-01-14 14:37:29.999000064,-0.500000,-0.500000,-0.500000,-0.445042,-0.366025,-0.633975,0.081366,0.361785,0.181765,-0.193497,-0.184678,-0.106744
50%,2022-01-14 09:15:00,0.000000,1.837623e-14,-1.730199e-14,0.000000,0.002721,2022-01-14 09:29:59.999000064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.503589,0.505631,0.500087,0.000000,0.000000,0.000000
75%,2024-01-13 16:22:30,0.503983,4.847444e-01,5.166936e-01,0.503577,0.535380,2024-01-13 16:37:29.999000064,0.500000,0.500000,0.500000,0.554958,0.633975,0.366025,0.924101,0.650315,0.818499,0.196613,0.184045,0.106310
max,2026-01-11 22:15:00,1635.799662,2.054075e+03,1.930858e+03,1632.325107,3.647380,2026-01-11 22:29:59.999000,0.707107,0.707107,0.623490,0.801938,0.732051,0.732051,412.695553,13568.603746,3.068995,305.632168,438.583677,375.552614
std,NaN,4.919811,6.033310e+00,5.800382e+00,4.913423,0.790527,NaN,0.499937,0.500065,0.452214,0.463839,0.517558,0.517704,7.148860,25.949135,0.446092,1.909196,2.146526,1.579556

In [19]:
df.isnull().sum()

Open time           1000
Open_diff           1000
High_diff           1000
Low_diff            1000
Close_diff          1000
Volume              1000
Close time          1000
hour_sin            1000
hour_cos            1000
day_of_week_sin     1000
day_of_week_cos     1000
month_sin           1000
month_cos           1000
Label_Q_Standard    1000
Label_Q_VWAP        1000
Label_Q_Gap         1000
VMD_Mode1              0
VMD_Mode2              0
VMD_Mode3              0
dtype: int64

In [20]:
df.dropna(inplace=True)

In [21]:
from statsmodels.tsa.stattools import adfuller

result = adfuller(df['Open_diff'], autolag='AIC')
print(f'ADF Statistic: {result[0]}')
print(f'p-value: {result[1]}')
print(f'n_lags: {result[1]}')

ADF Statistic: -152.95405782704486
p-value: 0.0
n_lags: 0.0

In [7]:
df.describe()

,Open time,Open_diff,High_diff,Low_diff,Close_diff,Volume,Close time,hour_sin,hour_cos,day_of_week_sin,...,day_of_week_sin_diff,day_of_week_cos_diff,month_sin_diff,month_cos_diff,Label_Q_Standard_diff,Label_Q_VWAP_diff,Label_Q_Gap_diff,VMD_Mode1_diff,VMD_Mode2_diff,VMD_Mode3_diff
count,280030,280030.000000,2.800300e+05,2.800300e+05,280030.000000,280030.000000,280030,280030.000000,280030.000000,280030.000000,...,280030.000000,280030.000000,2.800300e+05,2.800300e+05,2.800300e+05,2.800300e+05,2.800300e+05,280030.000000,2.800300e+05,2.800300e+05
mean,2022-01-13 12:55:57.132091904,0.001538,2.960475e-02,-2.937416e-02,0.001369,0.060815,2022-01-13 13:10:57.113961728,-0.000703,-0.000117,-0.000842,...,-0.000003,0.000004,3.964657e-22,3.964657e-22,7.006174e-07,6.497034e-07,5.683438e-07,-0.000005,-5.371029e-07,-6.598314e-07
min,2018-01-11 12:15:00,-1633.644380,-2.051661e+03,-1.930698e+03,-1632.300024,-4.500288,2018-01-11 12:29:59.999000,-0.707107,-0.707107,-0.623490,...,-0.554958,-0.554958,-3.660254e-01,-3.660254e-01,-3.719920e+03,-1.356877e+04,-3.617863e+00,-699.548214,-5.851785e+02,-5.792375e+02
25%,2020-01-14 14:33:45,-0.491874,-5.112144e-01,-4.795967e-01,-0.492443,-0.464389,2020-01-14 14:48:44.999000064,-0.500000,-0.500000,-0.500000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,-5.580888e-01,-1.254069e-01,-4.175830e-01,-0.138741,-2.079804e-01,-1.817952e-01
50%,2022-01-14 09:22:30,0.000000,1.837623e-14,-1.730199e-14,0.000000,0.002714,2022-01-14 09:37:29.999000064,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,-4.592065e-03,6.596646e-04,-4.176624e-03,-0.000741,-6.017887e-05,1.814254e-04
75%,2024-01-13 16:26:15,0.503983,4.847444e-01,5.166936e-01,0.503577,0.535381,2024-01-13 16:41:14.999000064,0.500000,0.500000,0.500000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,5.579994e-01,1.255796e-01,4.164547e-01,0.133720,2.074055e-01,1.828542e-01
max,2026-01-11 22:15:00,1635.799662,2.054075e+03,1.930858e+03,1632.325107,3.647380,2026-01-11 22:29:59.999000,0.707107,0.707107,0.623490,...,0.500000,0.554958,3.660254e-01,3.660254e-01,3.719124e+03,1.356700e+04,3.187121e+00,385.521814,7.003072e+02,7.018199e+02
std,NaN,4.919820,6.033317e+00,5.800392e+00,4.913426,0.790528,NaN,0.499938,0.500064,0.452215,...,0.040084,0.041117,4.961198e-03,4.961198e-03,1.010912e+01,3.669599e+01,6.490915e-01,2.009617,2.629314e+00,2.626613e+00

In [11]:
df.columns

Index(['Open time', 'Open_diff', 'High_diff', 'Low_diff', 'Close_diff',
       'Volume', 'Close time', 'hour_sin', 'hour_cos', 'day_of_week_sin',
       'day_of_week_cos', 'month_sin', 'month_cos', 'Label_Q_Standard',
       'Label_Q_VWAP', 'Label_Q_Gap', 'VMD_Mode1', 'VMD_Mode2', 'VMD_Mode3',
       'Open_diff_diff', 'High_diff_diff', 'Low_diff_diff', 'Close_diff_diff',
       'hour_sin_diff', 'hour_cos_diff', 'day_of_week_sin_diff',
       'day_of_week_cos_diff', 'month_sin_diff', 'month_cos_diff',
       'Label_Q_Standard_diff', 'Label_Q_VWAP_diff', 'Label_Q_Gap_diff',
       'VMD_Mode1_diff', 'VMD_Mode2_diff', 'VMD_Mode3_diff'],
      dtype='object')

In [ ]:
def _create_sequences(self, X, y):
    Xs, ys = [], []
    for i in range(len(X) - self.lookback):
        Xs.append(X[i:(i + self.lookback)])
        ys.append(y[i + self.lookback])
    return np.array(Xs), np.array(ys)